version: "3.9"
services:
  mongo:
    image: mongo
    container_name: mongo-db
    restart: on-failure
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  product-service:
    build: ./product-service
    image: siberia/product-service:v1.0
    container_name: product-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8380:8380"
    depends_on:
      - mongo

  search-service:
    build: ./search-service
    image: siberia/search-service:v1.0
    container_name: search-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8280:8280"
    depends_on:
      - mongo

  market-service:
    build: ./market-service
    image: siberia/market-service:v1.0
    container_name: market-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8180:8180"
    depends_on:
      - mongo