version: "3.9"
services:
  mongo:
    image: mongo
    container_name: mongo-db
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    restart: on-failure
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}

  postgres:
    image: library/postgres
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  order-service:
    build: ./order-service
    image: market/order-service:v1.0
    container_name: order-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      MONGO_ROOT_USER: ${MONGO_ROOT_USER}
      MONGO_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - "8480:8480"
    depends_on:
      - mongo

  product-service:
    build: ./product-service
    image: market/product-service:v1.0
    container_name: product-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      MONGO_ROOT_USER: ${MONGO_ROOT_USER}
      MONGO_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - "8380:8380"
    depends_on:
      - mongo

  inventory-service:
    build: ./inventory-service
    image: market/inventory-service:v1.0
    container_name: inventory-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8280:8280"
    depends_on:
      - mongo


volumes:
  db-data:
  mongodb:
  mongodb_config: