version: "3.9"
services:
  mongo:
    image: mongo
    container_name: mongo-db
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    restart: on-failure
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}

  product-service:
    build: ./product-service
    image: siberia/product-service:v1.0
    container_name: product-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      MONGO_ROOT_USER: ${MONGO_ROOT_USER}
      MONGO_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - "8380:8380"
    depends_on:
      - mongo

  search-service:
    build: ./search-service
    image: siberia/search-service:v1.0
    container_name: search-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8280:8280"
    depends_on:
      - mongo

  market-service:
    build: ./market-service
    image: siberia/market-service:v1.0
    container_name: market-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8180:8180"
    depends_on:
      - mongo

volumes:
  mongodb:
  mongodb_config: