CREATE TABLE IF NOT EXISTS product
(
    id          bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_uid uuid                                                NOT NULL,
    name        varchar(255)                                        NOT NULL
);
CREATE UNIQUE INDEX idx_product_product_uid ON product (product_uid);


CREATE TABLE IF NOT EXISTS orders
(
    id         bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_uid  uuid                                                NOT NULL,
    order_date timestamp                                           NOT NULL
);
CREATE UNIQUE INDEX idx_product_order_uid ON orders (order_uid);


CREATE TABLE IF NOT EXISTS order_item
(
    id             bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_item_uid uuid                                                NOT NULL,
    order_uid      uuid REFERENCES orders (order_uid)                  NOT NULL,
    product_uid    uuid REFERENCES product (product_uid)               NOT NULL,
    product_count  int                                                 NOT NULL
);
CREATE UNIQUE INDEX idx_order_item_order_item_uid ON order_item (order_item_uid);
CREATE INDEX idx_order_item_order_uid ON order_item (order_uid);
CREATE INDEX idx_order_item_product_uid ON order_item (product_uid);


CREATE TABLE IF NOT EXISTS warehouse
(
    id            bigint PRIMARY KEY NOT NULL,
    warehouse_uid uuid               NOT NULL,
    name          varchar(255)       NOT NULL
);
CREATE UNIQUE INDEX idx_warehouse_warehouse_uid ON warehouse (warehouse_uid);


CREATE TABLE stock
(
    registration_date timestamp                                 NOT NULL,
    document_type     int                                       NOT NULL,
    document_id       UUID                                      NOT NULL,
    row_id            int                                       NOT NULL,
    warehouse_uid     UUID REFERENCES warehouse (warehouse_uid) NOT NULL,
    product_uid       UUID REFERENCES product (product_uid)     NOT NULL,
    product_count     bigint                                    NOT NULL,
    CONSTRAINT pk_stock PRIMARY KEY (registration_date, document_type, document_id)
);
CREATE INDEX idx_stock_warehouse_uid ON stock (warehouse_uid);
CREATE INDEX idx_stock_product_uid ON stock (product_uid);
