CREATE TABLE IF NOT EXISTS item
(
    id          bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uid uuid                                                        NOT NULL,
    name        varchar(255)                                        NOT NULL
);
CREATE UNIQUE INDEX idx_item_uid ON item (uid);


CREATE TABLE stock
(
    registration_date timestamp                                 NOT NULL,
    document_type     int                                       NOT NULL,
    document_id       UUID                                      NOT NULL,
    record_id         int                                       NOT NULL,
    record_kind       int                                       NOT NULL,
    item_uid          UUID REFERENCES item (uid)                NOT NULL,
    item_count        bigint                                    NOT NULL,
    CONSTRAINT pk_stock PRIMARY KEY (registration_date, document_type, document_id, record_id)
);
CREATE INDEX idx_stock_item_uid ON stock (item_uid);
